name: Build and publish standalone package

on: 
  release:
    types: published
  workflow_dispatch:

env:
  ARTIFACT_PATH: project_artifacts    
  
jobs:  
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    permissions: write-all    
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install requirements pip
        run: pip install -r requirements.txt
      - name: Build 
        run: pyinstaller -F main.py
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:          
          name: google-photo-downloader-artifacts-${{ matrix.os }}
          path: ./dist/*
  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ${{ env.ARTIFACT_PATH }}
        pattern: google-photo-downloader-artifacts-*
    - name: Rename and list folder
      run: |
        for d in $ARTIFACT_PATH/*/ ; do mv $d $(echo $d | sed "s/artifacts-//; s/-latest//; s/ubuntu/linux/"); done
        ls -R $ARTIFACT_PATH
    - name: Zip artifacts
      run: | 
        for d in $ARTIFACT_PATH/*/ ; 
          do zip -r $d.zip $d
        done
        ls -R
    - name: Publish binary
      run: |
        files=$(ls *.zip)
        gh release upload ${{ github.ref_name }} $files
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}        
