name: Build and publish standalone package

on: 
  release:
    types: published
  workflow_dispatch:

jobs:
  build:
    matrix:
      os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    permissions: write-all
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install requirements pip
        run: pip install -r requirements.txt
      - name: Build 
        run: pyinstaller -F main.py
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:          
          name: format('google-photo-downloader-artifacts-{0}', ${{ matrix.os }})
          path: ./dist/*
          
      
     # - name: Publish binary
   #     run: |
    #      tar -czvf GooglePhotoDownloader.tar.gz ./dist/*
     #     gh release upload ${{ github.ref_name }} GooglePhotoDownloader.tar.gz
      #  env:
      #    GITHUB_TOKEN: ${{ github.TOKEN }}        
