name: Build and publish standalone package

on: 
  release:
    types: published
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install requirements pip
        run: pip install -r requirements.txt
      - name: Build 
        run: pyinstaller -F main.py
      - name: Publish binary
        run: |
          tar -czvf GooglePhotoDownloader.tar.gz ./dist/*
          gh release upload ${{ github.ref_name }} GooglePhotoDownloader.tar.gz
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}        
